name: Check the JavaScript source code in the viewer
on: [push]
jobs:
  code-check-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Run ESLint
      run: npm run lint:nofix
    - name: Run Jest
      run: npm run test
  create-container-image:
    runs-on: ubuntu-latest
    needs: code-check-and-test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: onikaze/okm-viewer-gitops:latest